[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn -c gunicorn.conf.py application:application"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
FLASK_ENV = "production"
ENABLE_RATE_LIMITING = "true" 